### ISSUE TITLE
这是一个Issue

### ISSUE THREAD

**Issue by frg2089** [shuiping233/github_aciton_test#1]
Issue的内容

![frg2089](https://avatars.githubusercontent.com/u/42184238)

那就一点中文好了）

123123

**Comment by frg2089** [comment]
真不容易啊

**Comment by frg2089** [comment]
评论

**Comment by shuiping233** [comment]
??

**Comment by shuiping233** [comment]
Oh Encoding!

**Comment by frg2089** [comment]
奇怪的issue

**Comment by frg2089** [comment]
.

**Comment by frg2089** [comment]
寄

**Comment by shuiping233** [comment]
悲


从 Windows 版邮件发送

发件人: 舰队的偶像-岛风酱！
发送时间: 2023年2月5日 17:55
收件人: shuiping233/github_aciton_test
抄送: shuiping; Comment
主题: Re: [shuiping233/github_aciton_test] 这是一个Issue (Issue #1)

寄

**Comment by frg2089** [comment]
> 悲 从 Windows 版邮件发送 发件人: 舰队的偶像-岛风酱！ 发送时间: 2023年2月5日 17:55 收件人: shuiping233/github_aciton_test 抄送: shuiping; Comment 主题: Re: [shuiping233/github_aciton_test] 这是一个Issue (Issue #1) 寄 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

草 邮件也是会激活action的
